### ISSUE TITLE
Null safety error

### ISSUE THREAD

**Issue by mergengerel** [what3words/w3w-dart-wrapper#2]
Because every version of what3words depends on json_serializable ^3.3.0 and json_serializable >=3.5.1 <4.0.0-nullsafety.0 depends on analyzer >=0.39.0 <0.42.0, every version of what3words requires analyzer >=0.39.0 <0.42.0 or json_serializable >=3.3.0 <3.5.1.
And because json_serializable >=3.5.0 <3.5.1 depends on analyzer >=0.39.0 <0.41.0 and json_serializable >=3.2.4 <3.5.0 depends on analyzer ^0.39.0, every version of what3words requires analyzer >=0.39.0 <0.42.0.
And because intl_utils 2.1.0 depends on analyzer ^1.0.0 and no versions of intl_utils match >2.1.0 <3.0.0, what3words is incompatible with intl_utils ^2.1.0.

**Comment by andycurriew3w** [comment]
Hello,

Thank you for reporting. We'll be working on making the wrapper null safe over the next few weeks and we will have this included in the next version.

Many thanks,

Andy

**Comment by mani-apps** [comment]
Hello @mergengerel we have updated our wrapper, you can find it [here](https://pub.dev/packages/what3words/versions/3.1.0-nullsafety.3)

w3w-dart-wrapper is now null safe, we will keep it as pre-release for now while gathering some feedback, let us know if this update fixes your issue so we can close it.

Many thanks,
Mani

**Comment by mergengerel** [comment]
Hello, Good job!, Thank you!
