### ISSUE TITLE
Missing export for autosuggest-options and Response 

### ISSUE THREAD

**Issue by Werkaninchen** [what3words/w3w-dart-wrapper#4]
The nullsafe version is missing the exports for response and autosuggest-options type as such the complete implementation has to be imported to the code. This is considered to be bad practice and should be changed.

offending files are:

- 'package:what3words/src/response/response.dart';
-  'package:what3words/src/response/autosuggest_options.dart';

https://dart-lang.github.io/linter/lints/implementation_imports.html

**Comment by mani-apps** [comment]
Thanks for your contribution @Werkaninchen , just to let you know 3.1.0 is now released to the stable channel with your suggested change.

If you are happy with the changes could you please close this issue?

Best,
Mani
