### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by t-m-z** [what3words/w3w-dart-wrapper#7]
regarding my flutter/dart-project I receive the follwong error:

Because what3words >=3.1.0 depends on chopper ^4.0.1 which depends on http >=0.13.0 <1.0.0, what3words >=3.1.0 requires http >=0.13.0 <1.0.0.
So, because gc_wizard depends on both http ^1.1.0 and what3words ^3.1.0, version solving failed.

When downgrading the http-lib to <1.0.0 I get another dependeny conflict.
On the other hand, the current version of chopper is 7.0.6 which depends on http 1.1.0.

So updating the w3w-wrapper to uses chopper 7.o.6 would solve this conflict.
Hence I recommend to update pubspec.yaml and adjust the source files

**Comment by Vlad-Adrian** [comment]
hello, any updates on this one?

**Comment by trevor-nomadik** [comment]
@sonigeez is there an override we can use in dependencies to just use your branch rather than waiting for them to merge this?

**Comment by ManuCiao** [comment]
@t-m-z and @Vlad-Adrian we will update it asap.

**Comment by sonigeez** [comment]
@Vlad-Adrian i would suggest you to clone my repo in your codebase for more control over it

**Comment by SubutaDan** [comment]
@sonigeez Thanks very much for making your repo with the updated dependencies available.

**Comment by ManuCiao** [comment]
@t-m-z @Vlad-Adrian @sonigeez @SubutaDan @trevor-nomadik I have merged the updated could you please let me know if anything works fine from your end too? thanks

**Comment by SubutaDan** [comment]
Hi Manuela,

Thank you for releasing this change and for notifying me. In my testing the change resolves the dependency issue.

-Dan

On 13 September 2024 00:53:03 GMT+09:00, Manuela Sabatino ***@***.***> wrote:
>@t-m-z @Vlad-Adrian @sonigeez @SubutaDan @trevor-nomadik I have merged the updated could you please let me know if anything works fine from your end too? thanks
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/what3words/w3w-dart-wrapper/issues/7#issuecomment-2346664619
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Japan: +81 70 911 52405
US: +1 704 380 9253
UK: +44 7875 599 430
